"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js/react'

import _resource_card from './resource-card.bones.json'
import _search_recovery_panel from './search-recovery-panel.bones.json'
import _resources_catalog_search from './resources-catalog-search.bones.json'
import _resources_catalog_controls from './resources-catalog-controls.bones.json'
import _hero_search_quick_browse from './hero-search-quick-browse.bones.json'
import _hero_search_results from './hero-search-results.bones.json'
import _hero_search_empty from './hero-search-empty.bones.json'
import _resources_intro_discover from './resources-intro-discover.bones.json'
import _resources_intro_listing from './resources-intro-listing.bones.json'
import _resources_discover_sections from './resources-discover-sections.bones.json'
import _resources_discover_personalized from './resources-discover-personalized.bones.json'
import _resources_listing_shell from './resources-listing-shell.bones.json'
import _resources_route_shell from './resources-route-shell.bones.json'
import _resource_detail_shell from './resource-detail-shell.bones.json'
import _purchase_card from './purchase-card.bones.json'
import _settings_page from './settings-page.bones.json'
import _admin_settings_page from './admin-settings-page.bones.json'
import _creator_apply_page from './creator-apply-page.bones.json'
import _admin_resource_form from './admin-resource-form.bones.json'
import _creator_resource_form from './creator-resource-form.bones.json'
import _creator_dashboard_overview from './creator-dashboard-overview.bones.json'
import _creator_dashboard_analytics from './creator-dashboard-analytics.bones.json'
import _creator_dashboard_resources from './creator-dashboard-resources.bones.json'
import _creator_dashboard_sales from './creator-dashboard-sales.bones.json'
import _creator_dashboard_profile from './creator-dashboard-profile.bones.json'
import _creator_resource_new_route from './creator-resource-new-route.bones.json'
import _login_form from './login-form.bones.json'
import _admin_analytics_overview from './admin-analytics-overview.bones.json'
import _admin_analytics_recommendations from './admin-analytics-recommendations.bones.json'
import _admin_analytics_ranking from './admin-analytics-ranking.bones.json'
import _admin_analytics_ranking_experiment from './admin-analytics-ranking-experiment.bones.json'
import _admin_analytics_purchases from './admin-analytics-purchases.bones.json'
import _admin_analytics_creator_activation from './admin-analytics-creator-activation.bones.json'
import _dashboard_overview from './dashboard-overview.bones.json'
import _dashboard_library from './dashboard-library.bones.json'
import _dashboard_downloads from './dashboard-downloads.bones.json'
import _dashboard_purchases from './dashboard-purchases.bones.json'
import _dashboard_subscription from './dashboard-subscription.bones.json'
import _dashboard_resources_redirect from './dashboard-resources-redirect.bones.json'

registerBones({
  "resource-card": _resource_card,
  "search-recovery-panel": _search_recovery_panel,
  "resources-catalog-search": _resources_catalog_search,
  "resources-catalog-controls": _resources_catalog_controls,
  "hero-search-quick-browse": _hero_search_quick_browse,
  "hero-search-results": _hero_search_results,
  "hero-search-empty": _hero_search_empty,
  "resources-intro-discover": _resources_intro_discover,
  "resources-intro-listing": _resources_intro_listing,
  "resources-discover-sections": _resources_discover_sections,
  "resources-discover-personalized": _resources_discover_personalized,
  "resources-listing-shell": _resources_listing_shell,
  "resources-route-shell": _resources_route_shell,
  "resource-detail-shell": _resource_detail_shell,
  "purchase-card": _purchase_card,
  "settings-page": _settings_page,
  "admin-settings-page": _admin_settings_page,
  "creator-apply-page": _creator_apply_page,
  "admin-resource-form": _admin_resource_form,
  "creator-resource-form": _creator_resource_form,
  "creator-dashboard-overview": _creator_dashboard_overview,
  "creator-dashboard-analytics": _creator_dashboard_analytics,
  "creator-dashboard-resources": _creator_dashboard_resources,
  "creator-dashboard-sales": _creator_dashboard_sales,
  "creator-dashboard-profile": _creator_dashboard_profile,
  "creator-resource-new-route": _creator_resource_new_route,
  "login-form": _login_form,
  "admin-analytics-overview": _admin_analytics_overview,
  "admin-analytics-recommendations": _admin_analytics_recommendations,
  "admin-analytics-ranking": _admin_analytics_ranking,
  "admin-analytics-ranking-experiment": _admin_analytics_ranking_experiment,
  "admin-analytics-purchases": _admin_analytics_purchases,
  "admin-analytics-creator-activation": _admin_analytics_creator_activation,
  "dashboard-overview": _dashboard_overview,
  "dashboard-library": _dashboard_library,
  "dashboard-downloads": _dashboard_downloads,
  "dashboard-purchases": _dashboard_purchases,
  "dashboard-subscription": _dashboard_subscription,
  "dashboard-resources-redirect": _dashboard_resources_redirect,
})
